import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import projectsRouter from "./projects.js";
import historyRouter from "./history.js";
import dashboardRouter from "./dashboard.js";
import authRouter from "./authRoutes.js";
import adminOperationalReadOnlyRouter from "./adminOperationalReadOnly.js";
import adminUsersReadOnlyRouter from "./adminUsersReadOnly.js";
import adminFinanceReadOnlyRouter from "./adminFinanceReadOnly.js";
import adminRouter from "./admin.js";
import adminManualDeleteRouter from "./adminManualDelete.js";
import creditsRouter from "./credits.js";
import aiRouter from "./ai.js";
import stripeRouter from "./stripe.js";
import stripeDiagnosticsRouter from "./stripeDiagnostics.js";
import waitlistRouter from "./waitlist.js";
import feedbackRouter from "./feedback.js";
import notificationsRouter from "./notifications.js";
import promptsRouter from "./prompts.js";
import userAnalyticsRouter from "./userAnalytics.js";
import referralRouter from "./referral.js";
import adminGrowthRouter from "./adminGrowth.js";
import adminRegisteredPlansRouter from "./adminRegisteredPlans.js";
import metaRouter from "./meta.js";
import shopeeRouter from "./shopee.js";
import mlRouter from "./ml.js";
import hotmartRouter from "./hotmart.js";
import kiwifyRouter from "./kiwify.js";
import integrationsRouter from "./integrations.js";
import trashRouter from "./trash.js";
import mlUserRouter from "./mlUserRoutes.js";
import adminApiConfigRouter from "./adminApiConfig.js";
import tiktokRouter from "./tiktok.js";
import savedItemsRouter from "./savedItems.js";
import kiwifyOAuthExperimentRouter from "./kiwifyOAuthExperiment.js";
import helpRouter from "./help.js";
import videosRouter from "./videos.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(projectsRouter);
router.use(historyRouter);
router.use(dashboardRouter);
router.use(authRouter);
router.use(adminOperationalReadOnlyRouter);
router.use(adminUsersReadOnlyRouter);
router.use(adminFinanceReadOnlyRouter);
router.use(adminRouter);
router.use(adminManualDeleteRouter);
router.use(adminGrowthRouter);
router.use(adminRegisteredPlansRouter);
router.use(creditsRouter);
router.use(aiRouter);
router.use(stripeRouter);
router.use(stripeDiagnosticsRouter);
router.use(waitlistRouter);
router.use(feedbackRouter);
router.use(notificationsRouter);
router.use(promptsRouter);
router.use(userAnalyticsRouter);
router.use(referralRouter);
router.use(metaRouter);
router.use(shopeeRouter);
router.use(mlRouter);
router.use(hotmartRouter);
router.use(kiwifyRouter);
router.use(integrationsRouter);
router.use(trashRouter);
router.use(mlUserRouter);
router.use(adminApiConfigRouter);
router.use(tiktokRouter);
router.use(savedItemsRouter);
router.use(kiwifyOAuthExperimentRouter);
router.use(helpRouter);
router.use(videosRouter);

export default router;
